// sdk/typescript/src/components/LoginButton.tsx
/**
 * LoginButton Component
 * 
 * 开箱即用的登录按钮组件
 */

import React from 'react';
import { useSSO } from '../hooks/useSSO';

export interface LoginButtonProps {
  authhubUrl: string;
  redirectUri?: string;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
  onLoginSuccess?: (user: any) => void;
}

/**
 * 登录按钮组件
 * 
 * @example
 * ```tsx
 * <LoginButton authhubUrl="http://localhost:8000">
 *   使用飞书登录
 * </LoginButton>
 * ```
 */
export const LoginButton: React.FC<LoginButtonProps> = ({
  authhubUrl,
  redirectUri,
  className,
  style,
  children = '登录',
  onLoginSuccess,
}) => {
  const { login, isLoading } = useSSO({
    authhubUrl,
    redirectUri,
    onLoginSuccess,
  });

  const defaultStyle: React.CSSProperties = {
    padding: '10px 20px',
    fontSize: '16px',
    backgroundColor: '#1890ff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
    ...style,
  };

  return (
    <button
      onClick={login}
      disabled={isLoading}
      className={className}
      style={defaultStyle}
      onMouseEnter={(e) => {
        e.currentTarget.style.backgroundColor = '#40a9ff';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.backgroundColor = '#1890ff';
      }}
    >
      {isLoading ? '加载中...' : children}
    </button>
  );
};

// sdk/typescript/src/components/vue/LoginButton.vue
<template>
  <button
    @click="login"
    :disabled="isLoading"
    :class="className"
    :style="buttonStyle"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    {{ isLoading ? '加载中...' : buttonText }}
  </button>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useSSO } from '../../composables/useSSO';

interface Props {
  authhubUrl: string;
  redirectUri?: string;
  className?: string;
  style?: Record<string, string>;
  buttonText?: string;
  onLoginSuccess?: (user: any) => void;
}

const props = withDefaults(defineProps<Props>(), {
  buttonText: '登录',
});

const { login: ssoLogin, isLoading } = useSSO({
  authhubUrl: props.authhubUrl,
  redirectUri: props.redirectUri,
  onLoginSuccess: props.onLoginSuccess,
});

const isHovered = ref(false);

const buttonStyle = computed(() => ({
  padding: '10px 20px',
  fontSize: '16px',
  backgroundColor: isHovered.value ? '#40a9ff' : '#1890ff',
  color: 'white',
  border: 'none',
  borderRadius: '4px',
  cursor: 'pointer',
  transition: 'background-color 0.3s',
  ...props.style,
}));

const login = () => {
  ssoLogin();
};

const handleMouseEnter = () => {
  isHovered.value = true;
};

const handleMouseLeave = () => {
  isHovered.value = false;
};
</script>
