// sdk/typescript/examples/vue-sso/src/pages/Callback.vue
<template>
  <SSOCallback
    :authhubUrl="AUTHHUB_URL"
    redirectTo="/dashboard"
    :onSuccess="handleSuccess"
    :onError="handleError"
  />
</template>

<script setup lang="ts">
import { SSOCallback } from '@authhub/sdk/components/vue';
import { AUTHHUB_URL } from '../config';

const handleSuccess = (token: string) => {
  console.log('Token交换成功:', token);
};

const handleError = (error: Error) => {
  console.error('登录失败:', error);
};
</script>

// sdk/typescript/examples/react-sso/src/pages/Callback.tsx
import React from 'react';
import { SSOCallback } from '@authhub/sdk/components';
import { AUTHHUB_URL } from '../config';

function Callback() {
  return (
    <SSOCallback
      authhubUrl={AUTHHUB_URL}
      redirectTo="/dashboard"
      onSuccess={(token) => {
        console.log('Token交换成功:', token);
      }}
      onError={(error) => {
        console.error('登录失败:', error);
      }}
    />
  );
}

export default Callback;
