// sdk/typescript/examples/vue-sso/src/pages/Login.vue
<template>
  <LoginPage
    :authhubUrl="AUTHHUB_URL"
    title="Vue SSO 示例"
    subtitle="使用飞书账号登录"
    :onLoginSuccess="handleLoginSuccess"
  />
</template>

<script setup lang="ts">
import { LoginPage } from '@authhub/sdk/components/vue';
import { AUTHHUB_URL } from '../config';

const handleLoginSuccess = (user: any) => {
  console.log('登录成功:', user);
};
</script>

// sdk/typescript/examples/react-sso/src/pages/Login.tsx
import React from 'react';
import { LoginPage } from '@authhub/sdk/components';
import { AUTHHUB_URL } from '../config';

function Login() {
  return (
    <LoginPage
      authhubUrl={AUTHHUB_URL}
      title="React SSO 示例"
      subtitle="使用飞书账号登录"
      onLoginSuccess={(user) => {
        console.log('登录成功:', user);
      }}
    />
  );
}

export default Login;
